"""add slug to category

Revision ID: 9af348c3a9f3
Revises: e6f5224a1f75
Create Date: 2021-07-08 00:36:41.849497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af348c3a9f3'
down_revision = 'e6f5224a1f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
